
# drain / default settings
settings = {
    "HDFS": {
        "log_file": "HDFS/HDFS_2k.log",
        "log_format": "<Date> <Time> <Pid> <Level> <Component>: <Content>",
        "regex": [r"blk_-?\d+", r"(\d+\.){3}\d+(:\d+)?"],
        "st": 0.5,
        "depth": 4,
    },
    "Hadoop": {
        "log_file": "Hadoop/Hadoop_2k.log",
        "log_format": "<Date> <Time> <Level> \[<Process>\] <Component>: <Content>",
        "regex": [r"(\d+\.){3}\d+"],
        "st": 0.5,
        "depth": 4,
    },
    "Spark": {
        "log_file": "Spark/Spark_2k.log",
        "log_format": "<Date> <Time> <Level> <Component>: <Content>",
        "regex": [r"(\d+\.){3}\d+", r"\b[KGTM]?B\b", r"([\w-]+\.){2,}[\w-]+"],
        "st": 0.5,
        "depth": 4,
    },
    "Zookeeper": {
        "log_file": "Zookeeper/Zookeeper_2k.log",
        "log_format": "<Date> <Time> - <Level>  \[<Node>:<Component>@<Id>\] - <Content>",
        "regex": [r"(/|)(\d+\.){3}\d+(:\d+)?"],
        "st": 0.5,
        "depth": 4,
    },
    "BGL": {
        "log_file": "BGL/BGL_2k.log",
        "log_format": "<Label> <Timestamp> <Date> <Node> <Time> <NodeRepeat> <Type> <Component> <Level> <Content>",
        "regex": [r"core\.\d+"],
        "st": 0.5,
        "depth": 4,
    },
    "HPC": {
        "log_file": "HPC/HPC_2k.log",
        "log_format": "<LogId> <Node> <Component> <State> <Time> <Flag> <Content>",
        "regex": [r"=\d+"],
        "st": 0.5,
        "depth": 4,
    },
    "Thunderbird": {
        "log_file": "Thunderbird/Thunderbird_2k.log",
        "log_format": "<Label> <Timestamp> <Date> <User> <Month> <Day> <Time> <Location> <Component>(\[<PID>\])?: <Content>",
        "regex": [r"(\d+\.){3}\d+"],
        "st": 0.5,
        "depth": 4,
    },
    "Windows": {
        "log_file": "Windows/Windows_2k.log",
        "log_format": "<Date> <Time>, <Level>                  <Component>    <Content>",
        "regex": [r"0x.*?\s"],
        "st": 0.7,
        "depth": 5,
    },
    "Linux": {
        "log_file": "Linux/Linux_2k.log",
        "log_format": "<Month> <Date> <Time> <Level> <Component>(\[<PID>\])?: <Content>",
        "regex": [r"(\d+\.){3}\d+", r"\d{2}:\d{2}:\d{2}"],
        "st": 0.39,
        "depth": 6,
    },
    "Android": {
        "log_file": "Android/Android_2k.log",
        "log_format": "<Date> <Time>  <Pid>  <Tid> <Level> <Component>: <Content>",
        "regex": [
            r"(/[\w-]+)+",
            r"([\w-]+\.){2,}[\w-]+",
            r"\b(\-?\+?\d+)\b|\b0[Xx][a-fA-F\d]+\b|\b[a-fA-F\d]{4,}\b",
        ],
        "st": 0.2,
        "depth": 6,
    },
    "HealthApp": {
        "log_file": "HealthApp/HealthApp_2k.log",
        "log_format": "<Time>\|<Component>\|<Pid>\|<Content>",
        "regex": [],
        "st": 0.2,
        "depth": 4,
    },
    "Apache": {
        "log_file": "Apache/Apache_2k.log",
        "log_format": "\[<Time>\] \[<Level>\] <Content>",
        "regex": [r"(\d+\.){3}\d+"],
        "st": 0.5,
        "depth": 4,
    },
    "Proxifier": {
        "log_file": "Proxifier/Proxifier_2k.log",
        "log_format": "\[<Time>\] <Program> - <Content>",
        "regex": [
            r"<\d+\ssec",
            r"([\w-]+\.)+[\w-]+(:\d+)?",
            r"\d{2}:\d{2}(:\d{2})*",
            r"[KGTM]B",
        ],
        "st": 0.6,
        "depth": 3,
    },
    "OpenSSH": {
        "log_file": "OpenSSH/OpenSSH_2k.log",
        "log_format": "<Date> <Day> <Time> <Component> sshd\[<Pid>\]: <Content>",
        "regex": [r"(\d+\.){3}\d+", r"([\w-]+\.){2,}[\w-]+"],
        "st": 0.6,
        "depth": 5,
    },
    "OpenStack": {
        "log_file": "OpenStack/OpenStack_2k.log",
        "log_format": "<Logrecord> <Date> <Time> <Pid> <Level> <Component> \[<ADDR>\] <Content>",
        "regex": [r"((\d+\.){3}\d+,?)+", r"/.+?\s", r"\d+"],
        "st": 0.5,
        "depth": 5,
    },
    "Mac": {
        "log_file": "Mac/Mac_2k.log",
        "log_format": "<Month>  <Date> <Time> <User> <Component>\[<PID>\]( \(<Address>\))?: <Content>",
        "regex": [r"([\w-]+\.){2,}[\w-]+"],
        "st": 0.7,
        "depth": 6,
    },

    'Audit': {
        'log_file': 'Audit/Audit_2k.log',
        'log_format': "type=<Type> msg=audit\(<Time>\): <Content>",
        'regex': [],
        'st': 0.5,
        'depth': 10,
    }
}

brain_settings = {
    'Proxifier': {'delimiter': ['\\(.*?\\)'], 'theshold': 3},
    'HDFS': {'delimiter': [''], 'theshold': 2},
    'Hadoop': {'delimiter': [], 'theshold': 6},
    'Spark': {'delimiter': [], 'theshold': 4},
    'Zookeeper': {'delimiter': [], 'theshold': 3},
    'BGL': {'delimiter': [], 'theshold': 6},
    'HPC': {'delimiter': [], 'theshold': 5},
    'Thunderbird': {'delimiter': [], 'theshold': 3},
    'Windows': {'delimiter': [], 'theshold': 3},
    'Linux': {'delimiter': [''], 'theshold': 4},
    'Android': {'delimiter': [''], 'theshold': 5},
    'HealthApp': {'delimiter': [''], 'theshold': 4},
    'Apache': {'delimiter': [], 'theshold': 4},
    'OpenSSH': {'delimiter': [], 'theshold': 6},
    'OpenStack': {'delimiter': [], 'theshold': 5},
    'Mac': {'delimiter': [], 'theshold': 5},
    'Audit': {'delimiter': [], 'theshold': 4}
}

logram_settings = {
    'HDFS': {'doubleThreshold': 15, 'triThreshold': 10},
    'Hadoop': {'doubleThreshold': 9, 'triThreshold': 10},
    'Spark': {'doubleThreshold': 15, 'triThreshold': 10},
    'Zookeeper': {'doubleThreshold': 15, 'triThreshold': 10},
    'BGL': {'doubleThreshold': 92, 'triThreshold': 4},
    'HPC': {'doubleThreshold': 15, 'triThreshold': 10},
    'Thunderbird': {'doubleThreshold': 35, 'triThreshold': 32},
    'Windows': {'doubleThreshold': 15, 'triThreshold': 10},
    'Linux': {'doubleThreshold': 120, 'triThreshold': 100},
    'Android': {'doubleThreshold': 15, 'triThreshold': 10},
    'HealthApp': {'doubleThreshold': 15, 'triThreshold': 10},
    'Apache': {'doubleThreshold': 15, 'triThreshold': 10},
    'Proxifier': {'doubleThreshold': 500, 'triThreshold': 470},
    'OpenSSH': {'doubleThreshold': 88, 'triThreshold': 81},
    'OpenStack': {'doubleThreshold': 30, 'triThreshold': 25},
    'Mac': {'doubleThreshold': 2, 'triThreshold': 2},
    "Audit": {'doubleThreshold': 15, 'triThreshold': 10},
}

AEL_settings = {
    'HDFS': {'minEventCount': 2, 'merge_percent': 0.5},
    'Hadoop': {'minEventCount': 2, 'merge_percent': 0.4},
    'Spark': {'minEventCount': 2, 'merge_percent': 0.4},
    'Zookeeper': {'minEventCount': 2, 'merge_percent': 0.4},
    'BGL': {'minEventCount': 2, 'merge_percent': 0.5},
    'HPC': {'minEventCount': 5, 'merge_percent': 0.4},
    'Thunderbird': {'minEventCount': 2, 'merge_percent': 0.4},
    'Windows': {'minEventCount': 2, 'merge_percent': 0.4},
    'Linux': {'minEventCount': 2, 'merge_percent': 0.6},
    'Android': {'minEventCount': 2, 'merge_percent': 0.6},
    'HealthApp': {'minEventCount': 2, 'merge_percent': 0.6},
    'Apache': {'minEventCount': 2, 'merge_percent': 0.4},
    'Proxifier': {'minEventCount': 2, 'merge_percent': 0.4},
    'OpenSSH': {'minEventCount': 10, 'merge_percent': 0.7},
    'OpenStack': {'minEventCount': 6, 'merge_percent': 0.5},
    'Mac': {'minEventCount': 2, 'merge_percent': 0.6},
    "Audit": {'minEventCount': 2, 'merge_percent': 0.4},
}

SPELL_settings = {
    'HDFS': {'tau': 0.7},
    'Hadoop': {'tau': 0.7},
    'Spark': {'tau': 0.55},
    'Zookeeper': {'tau': 0.7},
    'BGL': {'tau': 0.75},
    'HPC': {'tau': 0.65},
    'Thunderbird': {'tau': 0.5},
    'Windows': {'tau': 0.7},
    'Linux': {'tau': 0.55},
    'Android': {'tau': 0.95},
    'HealthApp': {'tau': 0.5},
    'Apache': {'tau': 0.6},
    'Proxifier': {'tau': 0.85},
    'OpenSSH': {'tau': 0.8},
    'OpenStack': {'tau': 0.9},
    'Mac': {'tau': 0.6},
    "Audit": {'tau': 0.7},
}

# for key, value in logram_settings.items():
#     if key in settings:
#         settings[key].update(value)